name: automate crx test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      # setup repo directory
    - uses: actions/checkout@v3
      # setup python
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install packages
      working-directory: ./CRX3-Creator-master
      run: pip install -r requirements.txt
    - name: Run script
      working-directory: ./CRX3-Creator-master   
      run: python main.py ../src
    - name: Run upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: my-artifact-crx
        path: ${{ github.workspace }}/src.crx
